import { defineField, defineType } from 'sanity'

// Reusable portable text field factory
const editorialSection = (name: string, title: string, description?: string) =>
  defineField({
    name,
    title,
    type: 'object',
    description,
    fields: [
      defineField({
        name: 'headline',
        title: 'Headline',
        type: 'string',
        validation: Rule => Rule.required(),
      }),
      defineField({
        name: 'body',
        title: 'Body',
        type: 'array',
        of: [{ type: 'block' }],
        validation: Rule => Rule.required(),
      }),
    ],
  })

export default defineType({
  name: 'weeklyIssue',
  title: 'Weekly Issue',
  type: 'document',

  fields: [
    // ─── Identity ─────────────────────────────────────────────────────────────
    defineField({
      name: 'issueNumber',
      title: 'Issue Number',
      type: 'number',
      validation: Rule => Rule.required().integer().positive(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: (doc: any) => `issue-${doc.issueNumber}`, maxLength: 96 },
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'publishDate',
      title: 'Publish Date',
      type: 'date',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          { title: 'Draft', value: 'draft' },
          { title: 'In Review (Andrew)', value: 'in-review' },
          { title: 'Published', value: 'published' },
        ],
        layout: 'radio',
      },
      initialValue: 'draft',
      validation: Rule => Rule.required(),
    }),

    // ─── Featured Charity ──────────────────────────────────────────────────────
    defineField({
      name: 'charity',
      title: 'Featured Charity',
      type: 'reference',
      to: [{ type: 'charity' }],
      validation: Rule => Rule.required(),
    }),

    // ─── Visual Theme ──────────────────────────────────────────────────────────
    defineField({
      name: 'theme',
      title: 'Visual Theme',
      type: 'object',
      description: 'CSS-injectable theme variables generated by the Design agent',
      fields: [
        defineField({ name: 'primaryColor', title: 'Primary Color', type: 'string', description: 'Hex value, e.g. #1D9E75' }),
        defineField({ name: 'accentColor', title: 'Accent Color', type: 'string' }),
        defineField({ name: 'backgroundColor', title: 'Background Color', type: 'string' }),
        defineField({ name: 'textColor', title: 'Text Color', type: 'string' }),
        defineField({ name: 'fontDisplay', title: 'Display Font', type: 'string', description: 'Google Fonts name' }),
        defineField({ name: 'fontBody', title: 'Body Font', type: 'string', description: 'Google Fonts name' }),
        defineField({
          name: 'visualDirection',
          title: 'Visual Direction',
          type: 'text',
          rows: 3,
          description: 'Design agent\'s brief — what this issue should feel like aesthetically',
        }),
      ],
    }),

    // ─── Bonus Type ────────────────────────────────────────────────────────────
    defineField({
      name: 'bonusType',
      title: 'Rotating Bonus Category',
      type: 'string',
      options: {
        list: [
          { title: 'Big Budget Treatment', value: 'bigBudget' },
          { title: 'Write Them a Jingle', value: 'jingle' },
          { title: 'Spec Ad / Campaign', value: 'specAd' },
        ],
        layout: 'radio',
      },
      validation: Rule => Rule.required(),
    }),

    // ─── Editorial Sections ────────────────────────────────────────────────────
    editorialSection(
      'originStory',
      'Origin Story',
      'The weird, specific moment someone said "I guess I\'m doing this now." Not the polished About page version.'
    ),
    defineField({
      name: 'problemStatement',
      title: "The Problem They're Solving",
      type: 'object',
      description: 'Stated plainly and precisely. No sentiment. Just: here is the broken thing, here is how small the fix actually is.',
      fields: [
        defineField({
          name: 'headline',
          title: 'Headline',
          type: 'string',
          validation: Rule => Rule.required(),
        }),
        defineField({
          name: 'body',
          title: 'Body',
          type: 'array',
          of: [{ type: 'block' }],
          validation: Rule => Rule.required(),
        }),
        // ─── PDF source content (Phase 6 — WeasyPrint renderer reads from here) ──
        defineField({
          name: 'pdfContent',
          title: 'PDF Content (source for problemPdf)',
          type: 'object',
          description:
            'Structured source for the Problem Statement PDF. The WeasyPrint renderer reads this exact shape; field names match the Phase 5 ProblemWriter Pydantic contract. Andrew may edit stats/sources here without re-running the pipeline.',
          fields: [
            defineField({
              name: 'problemStatement',
              title: 'Problem Statement (PDF summary, <=150 words)',
              type: 'text',
              rows: 6,
            }),
            defineField({
              name: 'keyDataPoints',
              title: 'Key Data Points (exactly 3)',
              type: 'array',
              of: [
                {
                  type: 'object',
                  fields: [
                    defineField({ name: 'stat', title: 'Statistic', type: 'string' }),
                    defineField({ name: 'source', title: 'Source', type: 'string' }),
                  ],
                  preview: { select: { title: 'stat', subtitle: 'source' } },
                },
              ],
              validation: Rule =>
                Rule.length(3).error('keyDataPoints must contain exactly 3 entries (Phase 6 PDF layout depends on it)'),
            }),
            defineField({
              name: 'interventionMechanism',
              title: 'Intervention Mechanism (<=100 words)',
              type: 'text',
              rows: 4,
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'problemPdf',
      title: 'Problem Statement PDF',
      type: 'file',
      description: 'Generated PDF download — the narrative framework sales deck. Populated by the pipeline after generation.',
      options: { accept: '.pdf' },
    }),
    editorialSection(
      'founderBio',
      'Founder Bio',
      'Jesse voice, played completely straight. Every founder gets the Fortune 500 treatment.'
    ),
    defineField({
      name: 'caseStudy',
      title: 'Case Study',
      type: 'object',
      description: 'One real person, one real outcome. Proof of existence.',
      fields: [
        defineField({
          name: 'subjectName',
          title: 'Subject Name',
          type: 'string',
          description: 'Real or anonymized — Andrew\'s call',
        }),
        defineField({
          name: 'headline',
          title: 'Headline',
          type: 'string',
          validation: Rule => Rule.required(),
        }),
        defineField({
          name: 'body',
          title: 'Body',
          type: 'array',
          of: [{ type: 'block' }],
          validation: Rule => Rule.required(),
        }),
      ],
    }),

    // ─── The Game ──────────────────────────────────────────────────────────────
    defineField({
      name: 'game',
      title: 'The Charity as a Simple Game',
      type: 'object',
      description: 'Self-contained HTML/JS that gamifies the charity\'s mission. Drop-in embed on the page.',
      fields: [
        defineField({
          name: 'headline',
          title: 'Headline',
          type: 'string',
          validation: Rule => Rule.required(),
        }),
        defineField({
          name: 'description',
          title: 'Short Description',
          type: 'string',
          description: 'One sentence explaining what the game does',
        }),
        defineField({
          name: 'embedCode',
          title: 'Embed Code',
          type: 'text',
          description: 'Self-contained HTML/JS. Must work inside a sandboxed <iframe>. No external dependencies.',
          rows: 8,
          validation: Rule => Rule.required(),
        }),
      ],
    }),

    // ─── Rotating Bonus ────────────────────────────────────────────────────────
    defineField({
      name: 'bonus',
      title: 'Rotating Bonus',
      type: 'object',
      description: 'Content varies by bonusType. Only populate fields relevant to the active type.',
      fields: [
        defineField({
          name: 'headline',
          title: 'Headline',
          type: 'string',
          validation: Rule => Rule.required(),
        }),
        defineField({
          name: 'body',
          title: 'Body',
          type: 'array',
          of: [{ type: 'block' }],
          description: 'Main content — campaign concept, jingle context, or big budget narrative',
        }),
        // Jingle-specific
        defineField({
          name: 'lyrics',
          title: 'Lyrics',
          type: 'text',
          rows: 6,
          description: 'Jingle only — the full lyrics',
        }),
        defineField({
          name: 'sunoPrompt',
          title: 'Suno Style Prompt',
          type: 'text',
          rows: 3,
          description: 'Jingle only — style prompt for Suno. Andrew runs this manually until API is wired.',
        }),
        defineField({
          name: 'sunoAudioUrl',
          title: 'Suno Audio URL',
          type: 'url',
          description: 'Jingle only — populated after Andrew or the pipeline generates the audio',
        }),
        // Big Budget / Spec Ad specific
        defineField({
          name: 'storyboards',
          title: 'Storyboard Images',
          type: 'array',
          of: [{ type: 'image' }],
          description: 'Big Budget and Spec Ad — optional visual storyboard frames',
        }),
      ],
    }),

    // ─── Podcast ──────────────────────────────────────────────────────────────
    defineField({
      name: 'podcast',
      title: 'NotebookLM Podcast',
      type: 'object',
      description: 'The weekly podcast generated from the selection deliberation transcript',
      fields: [
        defineField({
          name: 'audioFile',
          title: 'Audio File',
          type: 'file',
          description: 'Uploaded after NotebookLM generates the episode',
          options: { accept: 'audio/*' },
        }),
        defineField({
          name: 'deliberationTranscript',
          title: 'Deliberation Transcript',
          type: 'text',
          rows: 10,
          description: 'The raw agent deliberation text that NotebookLM uses as source material',
        }),
        defineField({
          name: 'podcastDescription',
          title: 'Episode Description',
          type: 'text',
          rows: 3,
          description: 'Short description shown below the audio player on the site',
        }),
        defineField({
          name: 'duration',
          title: 'Duration (seconds)',
          type: 'number',
          description: 'Populated automatically after upload',
        }),
      ],
    }),

    // ─── Selection Deliberation ────────────────────────────────────────────────
    defineField({
      name: 'selectionDeliberation',
      title: 'Selection Deliberation',
      type: 'object',
      description: 'The Scout\'s candidates and the Editor\'s reasoning. Source material for the podcast and deliberation layer.',
      fields: [
        defineField({
          name: 'candidates',
          title: 'Candidates',
          type: 'array',
          of: [
            {
              type: 'object',
              fields: [
                defineField({ name: 'charity', title: 'Charity', type: 'reference', to: [{ type: 'charity' }] }),
                defineField({ name: 'scoutSummary', title: 'Scout Summary', type: 'text', rows: 3 }),
                defineField({ name: 'advocateArgument', title: 'Advocate Argument', type: 'text', rows: 4 }),
                defineField({ name: 'advocateScore', title: 'Advocate Score (1–10)', type: 'number' }),
              ],
              preview: {
                select: { title: 'charity.name', subtitle: 'scoutSummary' },
              },
            },
          ],
        }),
        defineField({
          name: 'editorDecision',
          title: 'Editor Decision',
          type: 'text',
          rows: 4,
          description: 'Why this charity was selected over the others',
        }),
        defineField({
          name: 'runnerUpNotes',
          title: 'Runner-Up Notes',
          type: 'text',
          rows: 3,
          description: 'Brief note on why the other candidates weren\'t selected this week',
        }),
        // ── Phase 13 addition (DEL-CONV, DEL-CONV-02) ─────────────────────────
        defineField({
          name: 'conversation',
          title: 'Deliberation Conversation',
          type: 'array',
          description: 'Chronicler-dramatized dialogue turns for the chat render. Auto-generated by the pipeline. Plain prose, no Markdown.',
          of: [
            {
              type: 'object',
              fields: [
                defineField({
                  name: 'speaker',
                  title: 'Speaker',
                  type: 'string',
                  description: 'Persona id: scout | advocate | editor',
                  validation: Rule => Rule.required(),
                }),
                defineField({
                  name: 'text',
                  title: 'Text',
                  type: 'text',
                  rows: 3,
                  description: 'Plain string, no Markdown.',
                  validation: Rule => Rule.required(),
                }),
              ],
              preview: {
                select: { title: 'speaker', subtitle: 'text' },
                prepare: ({ title, subtitle }: { title: string; subtitle: string }) => ({
                  title: title?.toUpperCase() ?? 'UNKNOWN',
                  subtitle: subtitle?.slice(0, 80) ?? '',
                }),
              },
            },
          ],
        }),
      ],
    }),

    // ─── Narrator (Phase 16 — NRR-01) ─────────────────────────────────────────
    defineField({
      name: 'narrator',
      title: 'Narrator',
      type: 'reference',
      to: [{ type: 'narratorProfile' }],
      description: 'Optional narrator profile. Leave unset for default Jesse voice. Set to override all four narrative sections (Origin Story, Problem, Founder Bio, Case Study) + the deliberation conversation. Clicking the linked profile opens the Studio card showing exampleSamples (NRR-07 preview affordance).',
    }),

    // ─── Pipeline Metadata ─────────────────────────────────────────────────────
    defineField({
      name: 'pipelineMetadata',
      title: 'Pipeline Metadata',
      type: 'object',
      description: 'Written by the pipeline. Do not edit manually.',
      fields: [
        defineField({ name: 'runId', title: 'Run ID', type: 'string' }),
        defineField({ name: 'startedAt', title: 'Pipeline Started', type: 'datetime' }),
        defineField({ name: 'completedAt', title: 'Pipeline Completed', type: 'datetime' }),
        defineField({
          name: 'modelVersions',
          title: 'Model Versions',
          type: 'text',
          rows: 2,
          description: 'JSON: which model was used for which agent',
        }),
        // ── Phase 4 addition (CONTEXT D-22, D-24, OPS-03) ─────────────────────
        defineField({
          name: 'cost',
          title: 'Run Cost (JSON)',
          type: 'text',
          rows: 4,
          description: 'JSON: per-agent token + USD cost summary. Mirrors Convex pipelineRuns.cost. Read-only for Andrew.',
        }),
      ],
    }),
  ],

  preview: {
    select: {
      title: 'charity.name',
      subtitle: 'issueNumber',
      media: 'charity.image',
    },
    prepare({ title, subtitle }) {
      return {
        title: title ?? 'Untitled',
        subtitle: subtitle ? `Issue #${subtitle}` : 'No issue number',
      }
    },
  },
})
