// ─── Sanity-derived types ─────────────────────────────────────────────
// Single import point for apps/web (Phase 2) and any TypeScript code in
// packages/pipeline (Phase 4) to consume Sanity-generated types.
//
// Source of truth: apps/studio/sanity.types.ts (regenerated by
// `pnpm typegen`; committed to git per D-08).
//
// Phase 2 imports look like:
//   import type { WeeklyIssue, Charity, AgentProfile } from '@eisenbalm/shared'
//   // or, more narrowly:
//   import type { WeeklyIssue } from '@eisenbalm/shared/sanity-types'
//
// After any schema edit in apps/studio/schemas/, re-run `pnpm typegen`
// from repo root and commit the regenerated apps/studio/sanity.types.ts.
//
// Path is relative because workspace consumers resolve via package
// exports; the relative path here points from
//   packages/shared/src/sanity-types.ts
// to
//   apps/studio/sanity.types.ts
// i.e. up three levels (../../../) and into apps/studio/.
export type * from '../../../apps/studio/sanity.types'
